### ISSUE TITLE
Enable Mergify for this repo

### ISSUE THREAD

**Issue by nshalman** [tinkerbell/cluster-api-provider-tinkerbell#117]
## Expected Behaviour

Approved PR with ready-to-merge tag gets merged

## Current Behaviour

Approved PR with ready-to-merge tag doesn't get merged

**Comment by detiber** [comment]
Mergify documentation: https://docs.mergify.com/getting-started/
Mergify config for sandbox: https://github.com/tinkerbell/sandbox/blob/main/.mergify.yml

**Comment by detiber** [comment]
Resolved by #131
