### ISSUE TITLE
Mergify config not matching github actions jobs

### ISSUE THREAD

**Issue by detiber** [tinkerbell/cluster-api-provider-tinkerbell#137]
## Expected Behaviour

Mergify should merge when conditions are met, including the CI jobs defined in github actions

## Current Behaviour

Mergify fails to merge the pr, showing that `check-success=validate` is false even when all github actions have passed.

## Possible Solution

Based on https://docs.mergify.com/conditions/#about-status-checks, it looks like the configuration would be correct, in that the github actions `job` name is `validate`, however I believe it probably needs to be modified to take into account that the job is a matrix job.

Some investigation will need to be done to determine if we need to specify `check-success` for all combinations of the matrix job or if there is a way to configure it to check for a prefix or regex matching the matrix jobs.

**Comment by mmlb** [comment]
Hey @detiber I just ran into something similar in tink (iirc) which PR did you have trouble with?

**Comment by jacobweinstock** [comment]
I think we're good here. please reopen if not.
