### ISSUE TITLE
Support for node power management with cluster create and delete

### ISSUE THREAD

**Issue by pokearu** [tinkerbell/cluster-api-provider-tinkerbell#146]
When clusters are created/deleted with CAPT, the bare metal nodes have to be manually powered on and set to PXE boot for cluster create and need to be manually powered off after cluster delete to completely delete the cluster.

## Expected Behaviour

1. When the hardware CRDs are applied and those hardware CRDs are picked for a Machine, CAPT can perform an extra step to power on the nodes being made part of the cluster.
2. During cluster deletion, once a hardware CRD is released, i.e. its not tagged to a Machine. CAPT can set the next boot order to PXE and power off the nodes.

## Current Behaviour

1. Currently we manually power on nodes for cluster creation.
2. During delete, the nodes are left powered on and only the resources (templates, workflows) are deleted. Thus the cluster is still reachable since the API server is running.

## Possible Solution

An integration with a BMC power management service like [pbnj](https://github.com/tinkerbell/pbnj) would help automate power on/off for CAPT.

**Comment by crayzeigh** [comment]
#147 was held up on workflow approval, that's been pushed through and likely will need review once completed

**Comment by chrisdoherty4** [comment]
#147 still held up. Awaiting response from author.

**Comment by chrisdoherty4** [comment]
We're not integrating PBnJ to CAPT as we're integrating Rufio.

/close
