### ISSUE TITLE
Update cluster-api dependency to latest v1.1.x release

### ISSUE THREAD

**Issue by detiber** [tinkerbell/cluster-api-provider-tinkerbell#152]
Update to support the latest cluster-api release

**Comment by detiber** [comment]
This would be a good opportunity to also bring in some of the dependabot updates that require manual testing/verification:

- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/136
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/144
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/145
- https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/150

**Comment by micahhausler** [comment]
For anyone who picks this up, here's the CAPI docs on steps to take https://cluster-api.sigs.k8s.io/developer/providers/v1.0-to-v1.1.html

**Comment by vielmetti** [comment]
https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/144 has been merged, so we are 2/4.

**Comment by chrisdoherty4** [comment]
Everything outlined in https://github.com/tinkerbell/cluster-api-provider-tinkerbell/issues/152#issuecomment-1077775649 has either closed or merged. 

There are outstanding dependabot updates that we'll address in v0.3.
