### ISSUE TITLE
Structure review and a bit of refactoring if required

### ISSUE THREAD

**Issue by gianarb** [tinkerbell/cluster-api-provider-tinkerbell#2]
Ciao! As we spoke yesterday the boilerplate code comes from CAPP. But I think there are a few things that I would like to better understand. All the code generation part: go and swagger is a huge unknown. Make works but for me, it is all magic.

Plus if you know that foldering is wrong or things like that, please feel free to make it more in line with the CAPI way to do things.

**Comment by detiber** [comment]
Going to close this for now, as things are currently pretty well aligned with other Cluster API infrastructure providers.
