### ISSUE TITLE
v0.3

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/cluster-api-provider-tinkerbell#200]
[Discussion issue for 0.3](https://github.com/tinkerbell/cluster-api-provider-tinkerbell/milestone/3)

This release is focused on updating dependencies to use released versions and ensuring stability with the latest Tinkerbell stack.

**Comment by chrisdoherty4** [comment]
We need to introduce updated tink repo api types so we can take advantage of the improved template support in tink. We might consider doing this independently of Rufio updates given it will force consumes to make lots of changes if we do both in 0.3.

**Comment by displague** [comment]
What are your thoughts on the other open [0.3 milestone](https://github.com/tinkerbell/cluster-api-provider-tinkerbell/milestone/3) issues?

Particularly, #34 and #204.

**Comment by chrisdoherty4** [comment]
Personally, I think they can both be pushed to 0.4. We'll end up with 3 releases within a few months but I think that's fine given the state of the Tinkerbell project as a whole. 

#34 is more a triage exercise to see what _still_ needs addressing too, not to actually address anything.

**Comment by chrisdoherty4** [comment]
All dependabot updates are complete and some minor refactoring around stamping tool versions too.

**Comment by chrisdoherty4** [comment]
#214 is merged so we should be good for v0.3

**Comment by chrisdoherty4** [comment]
https://github.com/tinkerbell/cluster-api-provider-tinkerbell/releases/tag/v0.3.0
