### ISSUE TITLE
Fix Go module name or repository name

### ISSUE THREAD

**Issue by invidian** [tinkerbell/cluster-api-provider-tinkerbell#21]
Currently Go module name is following:
```
$ grep mod go.mod
module github.com/tinkerbell/cluster-api-provider-tinkerbell
```

and repository name is https://github.com/tinkerbell/cluster-api-provider-tink.

This breaks looking up packages documentation in https://go.dev/, as neither https://pkg.go.dev/github.com/tinkerbell/cluster-api-provider-tinkerbell or https://pkg.go.dev/github.com/tinkerbell/cluster-api-provider-tink are valid links.

We should either change module name and all imports or rename the repository.

I think this also affects `go get`'ing this repository.

**Comment by detiber** [comment]
@invidian @gianarb which approach do you prefer here? I'm fine with either standardizing on `cluster-api-provider-tinkerbell` or `cluster-api-provider-tink`

**Comment by invidian** [comment]
If we don't hit some weird name-length issues, I think renaming repo to `cluster-api-provider-tinkerbell` would be better.

**Comment by detiber** [comment]
Closing, thank you @jacobweinstock for renaming the repository
/close
