### ISSUE TITLE
Consider provisioning load balancer machine as part of cluster infrastructure

### ISSUE THREAD

**Issue by invidian** [tinkerbell/cluster-api-provider-tinkerbell#26]
In theory, as part of cluster controller, we could run a workflow for a single machine with e.g. HAProxy configured on it, which would act as a load balancer for the cluster. Such machine would have to expose an API to add and remove the machine.

While not perfect, this would allow having multiple controlplane machines and replacing them.

**Comment by vrabbi** [comment]
Capv moved away from this for many reasons and went with kube vip which i think is a better approach. At least until the CAPI LB provider proposal is implemented

**Comment by detiber** [comment]
The kube-vip approach is currently implemented through the cluster template.
