### ISSUE TITLE
how to try capt on real hardware

### ISSUE THREAD

**Issue by ydp** [tinkerbell/cluster-api-provider-tinkerbell#276]
I followed the quick-start guide to try capt, but nothing happens after apply hardware and cluster.yaml, I can see the cloud-init user data written into hardware CR, but in the machine side, nothing happens, looks like something is missing for real hardware use case, which is expected given the guide, I find no where to set the IPMI IP and credentials, capt has no way to control the OS provision process, however going through the issues, it looks like capt supports OS provision, just don't know how should I use this feature.

## Expected Behaviour

Expect to try capt on real hardware success following a guide and create a cluster successfully.
What I hoped it to provision K8s cluster on a bare metal which has nothing configured, except networking boot is set. Is this possible for capt?

## Current Behaviour

Nothing happens except user data is written into hardware, and hardware does not have any state.

## Possible Solution

A guide or some insight on this?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by jacobweinstock** [comment]
Hey @ydp, thanks for reporting this. The [quickstart](https://github.com/tinkerbell/cluster-api-provider-tinkerbell/blob/main/docs/QUICK-START.md) definitely is missing a section for doing power and boot calls. I will cut a ticket for.

In the short term you can follow the guide in [Rufio](https://github.com/tinkerbell/rufio/tree/main/docs) for BMC interactions or manually power on the machines into a netbooting state.

**Comment by jacobweinstock** [comment]
Issue created. https://github.com/tinkerbell/cluster-api-provider-tinkerbell/issues/285

**Comment by ydp** [comment]
Thank you @jacobweinstock  I will try the Rufio guide first! Closing this issue now.
