### ISSUE TITLE
0.5.3 segfaults if AllowPXE is not set in Hardware

### ISSUE THREAD

**Issue by rpardini** [tinkerbell/cluster-api-provider-tinkerbell#416]
https://github.com/tinkerbell/cluster-api-provider-tinkerbell/blob/5483611cd8b4858606bd263442a7565d0287c042/controllers/machine_reconcile_scope.go#L116

long story short: CAPT changes this field during operations. If we set this in our Hardware object templates (maintained by ArgoCD) we enter an infinite loop. Thus we don't set it... which causes CAPT to segfault. Workaround is to set it once, manually.

**Comment by jacobweinstock** [comment]
Hey @rpardini, this is actually not an issue for the top of tree on main as this field is not used anymore. This was changed in https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/405.
